filter:
    paths: [src/*]
checks:
    php:
        excluded_dependencies:
            - swoole/ide-helper
build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run
