filter:
    paths: [src/*]
checks:
    php:
        excluded_dependencies:
            - swoole/ide-helper
build:
    environment:
        postgresql: false
        redis: false
    tests:
        override:
            - composer check
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run
        php70:
            environment:
                php: 7.0
        php71:
            environment:
                php: 7.1
        php72:
            environment:
                php: 7.2
