filter:
    paths: [src/*]
checks:
    php: true
build:
    environment:
        postgresql: false
        redis: false
    tests:
        override:
            - composer check
    dependencies:
        before:
            - pecl install swoole-2.0.12
    nodes:
        php70:
            environment:
                php: 7.0
        php71:
            environment:
                php: 7.1
        php72:
            environment:
                php: 7.2
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
