filter:
    paths: [src/*]
build:
    environment:
        postgresql: false
        redis: false
    tests:
        override:
            - composer check
    nodes:
        php70:
            environment:
                php: 7.0
        php71:
            environment:
                php: 7.1
        php72:
            environment:
                php: 7.2
