filter:
    paths: [src/*]
checks:
    php: true
build:
    environment:
        postgresql: false
        redis: false
    nodes:
        old:
            environment:
                php: 7.1
            dependencies:
                override:
                    - yes | pecl install inotify swoole-2.0.10
                    - composer update --prefer-lowest --no-interaction
                    - composer show
            tests:
                override:
                    - composer test
        latest:
            environment:
                php: 7.2
            dependencies:
                override:
                    - yes | pecl install inotify swoole-2.2.0 xdebug
                    - composer update --no-interaction
                    - composer show
            tests:
                override:
                    - composer cs-check
                    - command: composer test-coverage
                      coverage:
                          file: 'test/reports/coverage.xml'
                          format: 'clover'
                    - php-scrutinizer-run
