filter:
    paths: [src/*]
checks:
    php: true
build:
    environment:
        postgresql: false
        redis: false
    nodes:
        old:
            environment:
                php: 7.0
            dependencies:
                override:
                    - yes | pecl install swoole-2.0.10
                    - composer update --prefer-lowest --no-interaction
                    - composer show
            tests:
                override:
                    - composer check
        fresh:
            environment:
                php: 7.2
            dependencies:
                override:
                    - yes | pecl install swoole-2.1.0
                    - composer update --no-interaction
                    - composer show
            tests:
                override:
                    - composer check
                    - php-scrutinizer-run
