language: php
sudo: required
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - 7.2

install:
  - sudo pecl install swoole
  - composer self-update
  - composer install -n

script:
  - composer check
