language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - 7.2

install:
  - git clone https://github.com/crocos/pecl-build.git $PHPENV_ROOT/plugins/pecl-build
  - phpenv pecl swoole
  - composer install -n

script:
  - composer check
